name: ci
on: [push]
permissions:
  contents: write
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy images
        run: |
          mkdir build/
          cp *.png build/
      - name: Marp Build (html)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: slide-deck.md -o build/slides.html
        env:
          MARP_USER: root:root
      - name: Marp Build (pdf)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: slide-deck.md --allow-local-files -o build/slides.pdf
        env:
          MARP_USER: root:root
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
